name: tempoid
description: A library to generate URL-friendly, unique, and short IDs that are sortable by time. Inspired by nanoid and UUIDv7.
version: 0.2.0
repository: https://github.com/temporal-id/tempoid-dart
homepage: https://tempoid.dev

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
